// CONTOH JIKA MENGGUNAKAN FILE JPG
// profilePic: require("../assets/images/ridho.jpg"),
import ProfilePlaceholder from "../assets/images/pp.svg";

export const TEAM_DATA = [
  {
    role: "Backend",
    members: [
      {
        id: "1",
        name: "Asep Jamaludin",
        code: "APJ",
        major: "Telecommunication Engineering",
        profilePic: ProfilePlaceholder,
        quote: "Talk is cheap. Show me the code.",
        socials: { instagram: "#", linkedin: "#", github: "#" },
      },
      {
        id: "2",
        name: "Abraham Benedick",
        code: "ABR",
        major: "Telecommunication Engineering",
        profilePic: ProfilePlaceholder,
        quote: "The best error message is the one that never appears.",
        socials: { instagram: "#", linkedin: "#", github: "#" },
      },
      {
        id: "3",
        name: "Aria",
        code: "belum",
        major: "Telecommunication Engineering",
        profilePic: ProfilePlaceholder,
        quote: "The best error message is the one that never appears.",
        socials: { instagram: "#", linkedin: "#", github: "#" },
      },
    ],
  },
  {
    role: "Frontend",
    members: [
      {
        id: "4",
        name: "Hilmy Baihaqi",
        code: "IMI",
        major: "Telecommunication Engineering",
        profilePic: ProfilePlaceholder,
        quote: "Make it work, make it right, make it fast.",
        socials: { instagram: "#", linkedin: "#", github: "#" },
      },
      {
        id: "5",
        name: "Aurelia Aisya Rachma",
        code: "URL",
        major: "Telecommunication Engineering",
        profilePic: ProfilePlaceholder,
        quote: "Good design is good business.",
        socials: { instagram: "#", linkedin: "#", github: "#" },
      },
      {
        id: "6",
        name: "syayid",
        code: "belum",
        major: "Telecommunication Engineering",
        profilePic: ProfilePlaceholder,
        quote: "Good design is good business.",
        socials: { instagram: "#", linkedin: "#", github: "#" },
      },
    ],
  },
  {
    role: "Machine Learning",
    members: [
      {
        id: "7",
        name: "Stephani Maria Sianturi",
        code: "TEP",
        major: "Science Data",
        profilePic: ProfilePlaceholder,
        quote: "In God we trust, all others must bring data.",
        socials: { instagram: "#", linkedin: "#", github: "#" },
      },
      {
        id: "8",
        name: "Septia Retno Puspita",
        code: "RTN",
        major: "Telecommunication Engineering",
        profilePic: ProfilePlaceholder,
        quote:
          "The goal is to turn data into information, and information into insight.",
        socials: { instagram: "#", linkedin: "#", github: "#" },
      },
      {
        id: "9",
        name: "Syahril Arvia Almazril",
        code: "AZN",
        major: "Information Technology",
        profilePic: ProfilePlaceholder,
        quote: "Without data, you're just another person with an opinion.",
        socials: { instagram: "#", linkedin: "#", github: "#" },
      },
    ],
  },
  {
    role: "Internet Of Things",
    members: [
      {
        id: "10",
        name: "Ridho Anugrah Mulyadi",
        code: "RAM",
        major: "Computer Engineering",
        profilePic: ProfilePlaceholder,
        quote: "The Internet of Things is not a concept; it is a network.",
        socials: { instagram: "#", linkedin: "#", github: "#" },
      },
      {
        id: "11",
        name: "Muhammad Lazuardi",
        code: "LAZ",
        major: "Telecommunication Engineering",
        profilePic: ProfilePlaceholder,
        quote: "Connecting everything, everywhere.",
        socials: { instagram: "#", linkedin: "#", github: "#" },
      },
      {
        id: "12",
        name: "Rivanda Abdillah",
        code: "RVN",
        major: "Telecommunication Engineering",
        profilePic: ProfilePlaceholder,
        quote: "Simplicity is the ultimate sophistication.",
        socials: { instagram: "#", linkedin: "#", github: "#" },
      },
    ],
  },
];
